flask/data/website/views/forms.py
from wtforms import StringField, SubmitField, TextField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length
from flask import flash
from data.database.user import User
from data.database.video import Video


class SearchForm(FlaskForm):
    search = StringField('search:', validators=[DataRequired(), Length(min=2, max=64)])

    submit = SubmitField('search')

    def validate_search(self, search):

        search = Video.query.filter(Video.title.ilike('{}{}{}'.format('%', search.data, '%'))).first()

        if search is None:
            flash('get rekt no results')
            raise ValueError('no results')


class RegistrationForm(FlaskForm):

    username = StringField('username:', validators=[DataRequired(), Length(min=2, max=64)])

    submit = SubmitField('sign up')

    def validate_username(self, username):

        user = User.query.filter_by(username=username.data).first()

        if user:
            flash('get rekt username taken')
            raise ValueError('username taken')


class LoginForm(FlaskForm):

    username = StringField('username:', validators=[DataRequired(), Length(min=2, max=64)])

    submit = SubmitField('login')

    def validate_username(self, username):

        user = User.query.filter_by(username=username.data).first()

        if user is None:
            flash('get rekt username dont exist')
            raise ValueError('username dont exist')


class CommentForm(FlaskForm):

    content = TextField('', validators=[DataRequired(), Length(min=1, max=80)])

    submit = SubmitField('posten')

    def validate_content(self, content):

        pass

flask/data/website/views/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__, template_folder='./../templates', static_folder='./../static', static_url_path='website/static', url_prefix='/')

from . import home, login, register, response, helpers, result, user, video

flask/data/website/views/helpers.py
from flask import redirect, url_for, render_template
from data import db
from . import main


@main.route('/test', methods=['GET', 'POST'])
def test():

    current_page_title = 'test'

    return render_template('test.html', current_page_title=current_page_title)


@main.route('/reset')
def reset():
    db.drop_all()
    db.create_all()

    from data import db_start

    return redirect(url_for('main.register'))

flask/data/website/views/home.py
from flask import render_template, request, redirect, url_for
from data.website.views.forms import SearchForm
from . import main


@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def index():

    current_page_title = 'home'

    searchform = SearchForm()
    if searchform.validate_on_submit():
        return redirect(url_for('main.result', search=request.form['search']))

    return render_template('index.html', searchform=searchform, current_page_title=current_page_title)

flask/data/website/views/login.py
from flask import render_template, request, flash, redirect, url_for, session
from flask_login import login_user, logout_user, login_required, current_user
from data.config import local_server_adress
from data.database.user import User
from data.website.views.forms import LoginForm
import requests
from flask_jwt_extended import decode_token
from . import main


@main.route('/login', methods=['GET', 'POST'])
def login():

    current_page_title = 'login'

    loginform = LoginForm()
    if loginform.validate_on_submit():
        data = {'username': loginform.username.data, 'password': 'test'}
        r = requests.post(local_server_adress + url_for('auth_api.login'), json=data).json()
        if r['status'] == 'success':
            jwt_decoded = decode_token(r['access_token'])
            user = User.query.filter_by(username=jwt_decoded['identity']).first()
            login_user(user)
            session[current_user.username] = r['access_token']
            flash('logged in successfully')
            return redirect(url_for('main.index'))
        else:
            flash('registration api error, maybe url host')
            flash(r)

        next = request.args.get('next')
        return redirect(next or url_for('main.login'))

    return render_template('login.html', current_page_title=current_page_title, loginform=loginform)


@main.route('logout')
@login_required
def logout():
    headers = {'Authorization': session[current_user.username]}
    requests.post(local_server_adress + url_for('auth_api.logout'), headers=headers)

    logout_user()
    return redirect(url_for('main.login'))

flask/data/website/views/register.py
from flask import render_template, flash, redirect, url_for, session
from flask_login import login_user, current_user
from data.database.user import User
from data.website.views.forms import RegistrationForm
import requests
from data.config import local_server_adress
from flask_jwt_extended import decode_token
from . import main


@main.route('/register', methods=['GET', 'POST'])
def register():

    current_page_title = 'registration'

    registrationform = RegistrationForm()
    if registrationform.validate_on_submit():
        data = {'username': registrationform.username.data, 'email': 'lul@kek.de', 'password': 'test'}
        r = requests.post(local_server_adress + url_for('user_api.register_user'), json=data).json()
        if r['status'] == 'success':
            r = requests.post(local_server_adress + url_for('auth_api.login'), json=data).json()
            if r['status'] == 'success':
                jwt_decoded = decode_token(r['access_token'])
                user = User.query.filter_by(username=jwt_decoded['identity']).first()
                flash('account created for {}'.format(user.username))
                login_user(user)
                session[current_user.username] = r['access_token']
                return redirect(url_for('main.index'))
            else:
                flash('login failed')
        else:
            flash('registration api error, maybe url host')
            flash(r)

    return render_template('register.html', current_page_title=current_page_title, registrationform=registrationform)

flask/data/website/views/response.py
from flask import render_template, redirect, url_for
from data import login_manager
from . import main


@main.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('main.login'))

flask/data/website/views/result.py
from flask import render_template
from data.database.video import Video
from . import main


@main.route('/result/<search>', methods=['GET', 'POST'])
def result(search):

    current_page_title = 'result'

    search = Video.query.filter(Video.title.ilike('{}{}{}'.format('%', search, '%'))).all()

    return render_template('results.html', search=search, current_page_title=current_page_title)

flask/data/website/views/user.py
from flask import render_template
from . import main


@main.route('/user/<name>', methods=['GET', 'POST'])
def user(name):

    current_page_title = 'user'

    return render_template('user.html', name=name, current_page_title=current_page_title)

flask/data/website/views/video.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user
from data import db
from data.database.comment import Comment
from data.database.video import Video
from sqlalchemy import desc
from data.website.views.forms import CommentForm
from data.config import local_files_path
from . import main


@main.route('/watch/<video_id>', methods=['GET', 'POST'])
def video(video_id):

    current_page_title = 'video'

    video = Video.query.filter_by(id=video_id).first()

    if video is None:
        return redirect(404)

    root = video.root

    filename = video.filename

    video_title = video.title

    video_author = video.author_id

    video_description = video.text

    video_root = local_files_path + 'videos/' + video_author + '/' + filename

    comments = Comment.query.filter_by(video_id=video_id).order_by(desc(Comment.id)).all()

    suggestions = Video.query.filter(Video.id != video_id).all()

    commentform = CommentForm()
    if commentform.validate_on_submit():

        comment = Comment(author_id=current_user.username, video_id=video_id, content=commentform.content.data)
        db.session.add(comment)
        db.session.commit()
        flash('posted')
        return redirect(url_for('main.video', video_id=video_id))

    return render_template('watch.html', video_id=video_id, comments=comments,
                            commentform=commentform, root=video_root, video_title=video_title,
                            video_description=video_description, video_author=video_author,
                            current_page_title=current_page_title, suggestions=suggestions)

flask/data/website/templates/breadcrumb.html
<nav class="n-breadcrumb" aria-label="breadcrumb">
  <ol class="breadcrumb" style="background-color: transparent;">
    <li class="breadcrumb-item"><a href="/">home</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ current_page }}</li>
  </ol>
</nav>

flask/data/website/templates/compose.html
{% block content %}
<button type="button" id="poop-button" class="btn btn-outline-info">poopen</button>
<div id="compose-poop-window" class="window">
  <div class="container" style="margin: 3rem;">
    <div class="window-content">
      <span id="close-compose-window" class="close-button">&times;</span>
      <hr>
      <div class="media">
        <div class="media-left">
          <img src="{{url_for('views.static', filename='images/test.jpg')}}" class="img-profil"/>
        </div>
        <div class="media-body">
          <div class="media-content">
            <form class="compose-poop-form" method="POST" action="">
              {{ poopform.hidden_tag() }}
              <fieldset >
                {{ poopform.content(id="compose-textarea", class="compose-textarea", placeholder="kek...") }}
              </fieldset>
              <div class="form-actions" style="float: right; padding-top: 1rem;">
                {{ poopform.submit(id="compose-submit-button", class="btn btn-primary btn-ghost") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flask/data/website/templates/footer.html
<!--
<footer class="footer" style="position: absolute; top: 95%; left: 50%; margin-right: -50%; margin-top: 3rem; transform: translate(-50%, -50%);">
  Version 0.1
</footer>
-->
{% include "scripts.html" %}

flask/data/website/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="container" id="searchform-container">
    <form method="POST" action="">
      {{ searchform.hidden_tag() }}
      <fieldset>
        {{ searchform.search(class="searchform-textarea", placeholder="search...") }}
      </fieldset>
    </form>
</div>
{% endblock content %}

flask/data/website/templates/layout.html
{% include "meta.html" %}
<body>
  {% include "navbar.html" %}
<div class="container">
  <div class="row">
    <div class="col">
      <div>
        {% include "messages.html" %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</div>
  {% include "footer.html" %}
</body>
</html>

flask/data/website/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <form method="POST" action="">
    {{ loginform.hidden_tag() }}
    <fieldset>
      {{ loginform.username(class="login-textarea", placeholder="username...") }}
    </fieldset>
  </form>
  <div class="login-info">
    <a href="/register" style="font-size: 16px;">dont have an account?</a>
  </div>
</div>
{% endblock content %}

flask/data/website/templates/messages.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div id="flash-message" class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span id="dismiss-flash" aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
{% block content %}{% endblock %}

flask/data/website/templates/meta.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- bootstrap css -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- plyr css -->
  <link rel="stylesheet" href="https://cdn.plyr.io/3.5.3/plyr.css" />
  <!-- main css -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='css/main.css') }}">

  {% if current_page_title %}
    <title>nickipedia - {{ current_page_title }}</title>
  {% else %}
    <title>nickipedia</title>
  {% endif %}
</head>

flask/data/website/templates/navbar.html
<div class="nav-header">
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="/">nickipedia</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">settings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">about</a>
        </li>
      </ul>
    </div>
  </nav>
  {% include "breadcrumb.html" %}
</header>
</div>

flask/data/website/templates/posts.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts %}
<div class="media" id="posts">
  <img src="{{url_for('views.static', filename='images/test.jpg')}}" class="align-self-center mr-3" id="img-profil"/>
  <div class="media-body">
    <div class="mt-0">{{ post.author.username }} @<a href="user/{{ post.author.username }}">{{ post.author.username }}</a></div>
    <div class="mb-0">{{ post.content }}</div>
  </div>
</div>
{% endfor %}
{% endblock content %}

flask/data/website/templates/results.html
{% extends "layout.html" %}
{% block content %}
<div class="container" style="margin-top: 3rem;">
  {% for result in search %}
  <div class="card mb-2" id="result-card" style="margin-right: auto; margin-left: auto;">
    <a href="/watch/{{ result.id }}" style="color: black;">
    <div class="row no-gutters">
      <div class="col-md-3">
        <img src="{{url_for('.static', filename='images/test.jpg')}}" class="card-img-top" id="card-img-result" alt="...">
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h5 class="card-title">{{ result.title }}</h5>
          <p class="card-text">{{ result.text }}</p>
        </div>
      </div>
    </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock content %}

flask/data/website/templates/scripts.html
<!-- js -->
  <!-- video player -->
  <script src="https://cdn.plyr.io/3.5.3/plyr.polyfilled.js"></script>
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- popper -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <!-- bootstrap -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- react components -->
  <script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>
  <!-- axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <!-- main js -->
  <script src="{{ url_for('.static', filename='js/bundle.js') }}" type="text/javascript"></script>

flask/data/website/templates/test.html
{% extends "layout.html" %}
{% block content %}
<div class="container" id="root" style="margin-top: 3rem;">
</div>
{% endblock content %}

flask/data/website/templates/watch.html
{% extends "layout.html" %}
{% block content %}
<div class="container" style="margin-top: 2.5rem;">
  <div class="row" style="width: 100%; padding: 1rem;">
    <div class="col-sm-9">
      <video class="card-img-top" poster="{{ root }}" id="player" ratio="4:3" style="width:100%; border-radius: 5px; outline: none;" playsinline controls>
        <source src="{{ root }}" type="video/mp4">
      </video>
      <div class="card" style="margin-top: 0.5rem; opacity: 0.95; background-color: #F5F5F5; border: 2px solid #ccc; border-radius: 5px;">
        <div class="card-body">
          <h1 class="card-title" style="z-index: 1;">{{ video_title }}</h1>
          <h5 class="card-subtitle"><a href="{{ url_for('main.user', name=video_author) }}" class="card-link">{{ video_author }}</a></h5>
          <br>
          <p class="card-text">{{ video_description }}</p>
        </div>
      </div>
      <div class="container">
          <div class="media">
            <img src="{{url_for('.static', filename='images/test.jpg')}}" class="align-self-start mr-3" id="img-profil"/>
            <div class="media-body">
              <div class="mb-0">
                <form class="compose-comment-form" method="POST" action="">
                  {{ commentform.hidden_tag() }}
                  <fieldset>
                    {{ commentform.content(id="compose-textarea", class="compose-textarea", placeholder="leave a comment...") }}
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-sm-3" style="background-color: transparent; opacity: 0.95;">
      {% for i in suggestions %}
      <div class="card" style="height: 150px; width: 150px; background-color: transparent; margin: 1rem; border-radius: 5px;">
        <a href="/watch/{{ i.id }}">
        <img src="{{url_for('.static', filename='images/background.jpg')}}" class="card-img-top" alt="..." style="border-radius: 5px;">
        <div class="card-img-overlay">
          <h5 class="card-title" style="font-size: 12px; color: black;">{{ i.title }}</h5>
        </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="container">
  <div class="col-8" style="margin-top: -1.5rem;">
  {% for comment in comments %}
  <div class="media" id="posts" style="opacity: 0.95; margin-left: 1rem; border: 2px solid #ccc;">
    <img src="{{url_for('.static', filename='images/test.jpg')}}" class="align-self-center mr-3" id="img-profil"/>
    <div class="media-body">
      <div class="mt-0">{{ comment.author.username }} @<a href="../user/{{ comment.author.username }}">{{ comment.author.username }}</a></div>
      <div class="mb-0">{{ comment.content }}</div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>
{% endblock content %}